name: joker
description: "A test Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  figma_squircle: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/HalvarEng-Blk.ttf
        - asset: assets/fonts/HalvarEng-Lt.ttf
        - asset: assets/fonts/HalvarEng-Md.ttf
        - asset: assets/fonts/HalvarEng-Rg.ttf
        - asset: assets/fonts/HalvarEng-XBd.ttf